runtime: java
env: flex
runtime_config:
  jdk: openjdk8
env_variables:
  SERVER_PORT: 8080
  SPRING_DATASOURCE_URL: 
  SPRING_DATASOURCE_USERNAME: 
  SPRING_DATASOURCE_PASSWORD: 
  SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  REST_COUNTRY_ACCESS_TOKEN: 
handlers:
- url: /.*
  script: this field is required, but ignored
manual_scaling: 
  instances: 1